#!/usr/bin/env bash

# /tmp/qtile-layouts.ndjson generated by qtile hooks
# example line:
# {"screens": [{"screen": 0, "group": "dev", "layout": "cols"}, {"screen": 1, "group": "doc", "layout": "cols"}], "groups_with_windows": ["www", "gtd", "coms", "dev"], "active_screen": 0}

generate_layout_widget() {
    local layout_data="$1"
    local monitor_id="$2"

    if [ -n "$layout_data" ]; then
        layout=$(echo "$layout_data" | jq -r ".screens[] | select(.screen == $monitor_id) | .layout" 2>/dev/null || echo "col")
    else
        layout="col"
    fi

    echo "(label :class \"layout\" :text \"$layout\")"
}

monitor_id="${1:-0}"

if [ -f /tmp/qtile-layouts.ndjson ]; then
    initial_data=$(tail -n1 /tmp/qtile-layouts.ndjson 2>/dev/null)
    generate_layout_widget "$initial_data" "$monitor_id"
else
    generate_layout_widget "" "$monitor_id"
fi

tail -n0 -F /tmp/qtile-layouts.ndjson 2>/dev/null | while read -r line; do
    generate_layout_widget "$line" "$monitor_id"
done